import {TokenOrganism} from './TokenOrganism';
import type {ObservationMetadata} from './token-observation';
import {useEffect,useMemo,useRef,useState} from 'react';
import {captureActivity,marketTokens,type Activity} from './market-activity';
import {createNetwork} from './particle-network';
import {exploreTokens} from './token-explorer';
import {tokenAppearance} from './token-appearance';
import {CHAINS,selectTokens,tokenKey,type Chain} from './token-selection';
import './agent-trading-jev.css';
import {PARAMETERS,PARAMETER_GROUPS,parameterFor,formatParameter} from './parameter-catalog';
export type Field={id:string;group:string;key:string;value:string|number|boolean;path:string};
export type Assessment={id:string;status:string;model:string;modelVersion:string;evaluatedAt:string;summary:string;fieldIds:string[]};
export type RankingEvidence={captureId:string;captureHash:string;receivedAt:string;window:string|null;rank:number|null;swaps:number|null;volume:number|null;liquidity:number|null;createdAt:number|null};
export type Token={firstSeenAt?:string;sceneAbsentSince?:number;ranking?:RankingEvidence|null;observationMetadata?:ObservationMetadata;logo?:string|null;id:string;name:string;chain:string;phase:string;fields:Field[];assessment?:Assessment;evidence?:{captureId:string;captureHash:string;receivedAt?:string;normalization?:string}};
export type CounterWindow={from:number;to:number;start:number;duration:number};
export type PresentationCycle={cycleId:string;startedAt:string;publishedAt:string;startsAt?:string;periodMs:number;durationMs?:number;sourceCount:number;expectedSources:number;missing:string[];status:'complete'|'partial';late:boolean};
export type GlobalFieldStats={networkTimelines?:Record<string,CounterWindow[]>;networkWindows?:Record<string,CounterWindow>;displayWindow?:CounterWindow;total:number;captures:number;byChain:Record<string,number>;startedAt:string;scope:string};
export type Capture={presentation?:PresentationCycle;collectionCycle?:{id:string;started_at:string;interval_seconds:number};batches?:Capture[];globalStats?:GlobalFieldStats;assessmentState?:string;mode:string;label:string;captureHash:string;source:string;tokens:Token[];receivedAt?:string;captureId?:string;normalization?:string;sources?:{chain:string;receivedAt:string;count:number;cadenceMs?:number;measuredCadenceMs?:number;endpoint?:string;fieldsPerSecond?:number}[]};
export function AgentTradingJev({capture,initialNetwork,connectionError=false}:{capture?:Capture;initialNetwork?:Chain|'all';connectionError?:boolean}){
 const host=useRef<HTMLDivElement>(null),network=useRef<ReturnType<typeof createNetwork>|null>(null);
 const [activeKey,setActiveKey]=useState<string|null>(null),[playing,setPlaying]=useState(()=>!window.matchMedia('(prefers-reduced-motion: reduce)').matches),[group,setGroup]=useState('All'),[error,setError]=useState(false),[fieldKey,setFieldKey]=useState<string|null>(null);
 const [tokenQuery,setTokenQuery]=useState(''),[page,setPage]=useState(0),[focused,setFocused]=useState(false);
 const [view,setView]=useState('market'),[activity,setActivity]=useState<Activity[]>([]),[totals,setTotals]=useState({captures:0,observed:0,changes:0});const previousCapture=useRef<Capture|undefined>(undefined);
 const [activityFilter,setActivityFilter]=useState('all');
 const [query,setQuery]=useState(''),[showMissing,setShowMissing]=useState(false);
 const [chain,setChain]=useState<Chain|'all'>(initialNetwork??(capture?.mode==='archive'?'all':'robinhood'));
 const [minMarketCap,setMinMarketCap]=useState(30000),[minLiquidity,setMinLiquidity]=useState(0);
 const selection=useMemo(()=>selectTokens(capture?.tokens??[],{chain,minMarketCap,minLiquidity}),[capture,chain,minMarketCap,minLiquidity]);
 const tokens=useMemo(()=>marketTokens(selection.tokens,view),[selection.tokens,view]),active=Math.max(0,tokens.findIndex(t=>tokenKey(t)===activeKey)),selected=tokens[active];
 const explorer=useMemo(()=>exploreTokens(tokens,{query:tokenQuery,page,selectedKey:selected?tokenKey(selected):null}),[tokens,tokenQuery,page,selected]);
 const sceneTokens=explorer.scene,sceneIndex=selected?sceneTokens.findIndex(t=>tokenKey(t)===tokenKey(selected)):-1;
 useEffect(()=>{if(selected&&tokenKey(selected)!==activeKey)setActiveKey(tokenKey(selected));},[selected,activeKey]);
 const chooseToken=(key:string)=>{setActiveKey(key);setFocused(true);};
 const filteredActivity=activity.filter(e=>activityFilter==='all'||activityFilter==='selected'&&e.token===(selected?tokenKey(selected):null)||e.kind===activityFilter);
 const evidence=selected?.evidence??capture;
 const field=selected?.fields.find(f=>f.key===fieldKey),definition=field&&parameterFor(field.key);
 const visibleParameters=PARAMETERS.filter(p=>(group==='All'||p.group===group)&&(!query||`${p.label} ${p.key}`.toLowerCase().includes(query.toLowerCase()))&&(showMissing||selected?.fields.some(f=>f.key===p.key)));
 const tokensRef=useRef(sceneTokens);tokensRef.current=sceneTokens;
 useEffect(()=>{if(!host.current)return;const instance=createNetwork(host.current,[],index=>{const token=tokensRef.current[index];if(token){setActiveKey(tokenKey(token));setFocused(true);}},()=>setError(true));network.current=instance;return()=>{instance.dispose();network.current=null;};},[]);
 useEffect(()=>{network.current?.setTokens(sceneTokens);},[sceneTokens]);
 useEffect(()=>{network.current?.select(sceneIndex);},[sceneIndex,sceneTokens]);
 useEffect(()=>{if(focused)network.current?.focus();else network.current?.resetView();},[focused,activeKey]);
 useEffect(()=>network.current?.setPlaying(playing),[playing]);
 useEffect(()=>{if(!capture)return;const delta=captureActivity(previousCapture.current,capture);previousCapture.current=capture;if(!delta.events.length)return;setActivity(old=>[...delta.events.reverse(),...old].slice(0,200));setTotals(old=>({captures:old.captures+delta.captures,observed:old.observed+delta.observed,changes:old.changes+delta.events.filter(e=>e.kind==='change').length}));network.current?.pulse(delta.changed);},[capture]);
 return <main className="neural-page">
  <header className="neural-top"><a href="/docs/#/agent-trading-jev">OMNIA <span>EYE</span></a><span className="neural-private">PRIVATE WORKSPACE</span><a href="/docs/#/agent-trading-jev">Documentation ↗</a></header>
  <div className="neural-title"><div><p>AGENT TRADING / JEV</p><h1>The living data field.</h1></div><div className="neural-status"><i/>{connectionError?'Data connection interrupted':capture?.mode==='live'?'Connected · local trending':capture?capture.label:'Data source disconnected'}<small>{capture?.mode==='live'?`Last capture: ${capture.receivedAt} · ${Date.now()-Date.parse(capture.receivedAt??'')>120000?'Delayed source':'Recent capture'} · source-reported values`:capture?'Archive inspection · not a live stream':'Waiting for observations'}</small></div></div>
  <div className="neural-market-modes"><button aria-pressed={view==='market'} onClick={()=>{setView('market');setPage(0);}}>Market</button><button aria-pressed={view==='discovery'} onClick={()=>{setView('discovery');setPage(0);}}>Discovery · new 24h</button><small>{view==='discovery'?'Source creation time within 24 hours. Unknown ages excluded.':'Current rankings across the selected networks.'}</small></div>
  <section className="neural-selection" aria-label="Token selection"><div className="neural-networks">{CHAINS.map(c=><button key={c.id} aria-pressed={chain===c.id} onClick={()=>setChain(c.id)}>{c.label}<small>{selection.counts[c.id]}</small>{capture?.sources&&<small>{capture.sources.find(s=>s.chain===c.id)?(Date.now()-Date.parse(capture.sources.find(s=>s.chain===c.id)!.receivedAt)>120000?'Delayed':'Recent'):'No source'}</small>}</button>)}<button aria-pressed={chain==='all'} onClick={()=>setChain('all')}>All networks</button></div>
   <div className="neural-thresholds"><label>Market cap minimum<select value={minMarketCap} onChange={e=>setMinMarketCap(Number(e.target.value))}><option value={0}>No minimum</option><option value={30000}>30,000</option><option value={100000}>100,000</option><option value={1000000}>1,000,000</option></select></label><label>Liquidity minimum<select value={minLiquidity} onChange={e=>setMinLiquidity(Number(e.target.value))}><option value={0}>No minimum</option><option value={5000}>5,000</option><option value={10000}>10,000</option><option value={30000}>30,000</option></select></label></div>
   <p>{tokens.length} of {selection.networkCount} tokens shown · source rank first · positions are per network{capture?.mode==='archive'?' · launch-phase capture':''}. Thresholds use source-reported values.{selection.unknownMarketCap>0?` ${selection.unknownMarketCap} unknown market caps.`:''}{selection.unknownLiquidity>0?` ${selection.unknownLiquidity} unknown liquidity values.`:''}</p>
  </section>
  <TokenOrganism token={selected} onField={setFieldKey}/>
  <div className="neural-layout"><section className="neural-stage" aria-label="Token parameter network"><div className="neural-stage-top"><span>MARKET OBSERVATORY · DRAG TO ORBIT</span><div className="neural-view-actions"><button onClick={()=>{setFocused(false);network.current?.resetView();}}>Overview</button><button aria-pressed={!playing} onClick={()=>setPlaying(!playing)}>{playing?'Pause pulses':'Resume pulses'}</button></div></div><div ref={host} className="neural-canvas"/>
  {!tokens.length&&<div className="neural-empty">{!capture?'Waiting for the data connection.':selection.networkCount===0?'No records for this network in the loaded capture.':'No tokens meet these filters.'}<small>{capture&&selection.networkCount===0?'Choose another network to inspect the available records.':capture?'Lower the thresholds to include more tokens.':''}</small></div>}{error&&<div className="neural-empty">3D is unavailable. Explore the records below.</div>}
  <div className="neural-stage-bottom"><div><strong>{sceneTokens.length} / {tokens.length}</strong><span>VISIBLE / ELIGIBLE TOKENS</span></div><div><strong>{tokens.reduce((n,t)=>n+t.fields.length,0)}</strong><span>CAPTURED FIELDS</span></div><div><strong>{totals.changes}</strong><span>VALUES CHANGED · SESSION</span></div></div></section>
  <aside className="neural-inspector"><p className="neural-eyebrow">TOKEN INSPECTOR</p><h2>{selected?.name||'No selection'}</h2><p className="neural-address">{selected?.id}</p><button className="neural-focus" disabled={!selected} onClick={()=>{setFocused(true);network.current?.focus();}}>Focus token ↗</button><div className="neural-tags"><span>{selected?.chain}</span><span>{selected?.phase.replaceAll('_',' ')}</span></div>
  <div className="neural-tabs">{PARAMETER_GROUPS.map(g=><button key={g} aria-pressed={group===g} onClick={()=>setGroup(g)}>{g}<small>{selected?.fields.filter(f=>g==='All'||f.group===g).length??0}</small></button>)}</div>
  <div className="neural-parameter-tools"><label>Find a parameter<input type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Volume, holders, risk…"/></label><label className="neural-missing"><input type="checkbox" checked={showMissing} onChange={e=>setShowMissing(e.target.checked)}/>Show missing fields</label><p>{selected?.fields.length??0} / {PARAMETERS.length} catalog fields received · {selected?.chain??'No network'}</p><small>Received {evidence?.receivedAt??'Time not supplied'}</small></div>
  <div className="neural-values">{visibleParameters.map(p=>{const f=selected?.fields.find(f=>f.key===p.key);return <button key={p.key} disabled={!f} aria-pressed={fieldKey===p.key} onClick={()=>setFieldKey(p.key)}><span>{p.label}<small>{p.unit}</small></span><strong>{f?formatParameter(f):'Not supplied'}</strong></button>;})}{!visibleParameters.length&&<p className="neural-parameter-empty">No matching parameters in this capture.</p>}</div>
  {field&&<div className="neural-evidence"><p>CAPTURE EVIDENCE</p><strong>{definition?.label??field.key}: {formatParameter(field)}</strong><small>{definition?.note}</small><code>Raw: {String(field.value)}</code><code>{field.path}</code><small>Received: {evidence?.receivedAt??'Not supplied'}</small><small>Capture: {evidence?.captureId??'Not supplied'} · {evidence?.normalization??'Normalization unknown'}</small><small>Field: {field.id}</small><code>SHA-256 {evidence?.captureHash}</code></div>}
</aside></div>
  <section className="neural-explorer" aria-label="Token explorer"><div className="neural-explorer-toolbar"><label>Find a token<input type="search" placeholder="Name or contract address" value={tokenQuery} onChange={e=>{setTokenQuery(e.target.value);setPage(0);}}/></label><span>{explorer.matches} matches · {tokens.length} eligible</span><div><button disabled={explorer.page===0} onClick={()=>setPage(explorer.page-1)}>Previous</button><span>{explorer.page+1} / {explorer.pages}</span><button disabled={explorer.page+1>=explorer.pages} onClick={()=>setPage(explorer.page+1)}>Next</button></div></div><div className="neural-token-grid">{explorer.rows.map(t=><button key={tokenKey(t)} aria-pressed={selected&&tokenKey(t)===tokenKey(selected)} onClick={()=>chooseToken(tokenKey(t))}><i style={{background:tokenAppearance(t).color}}/><span><strong>{t.name}</strong><small>{t.chain} · {t.id.slice(0,6)}…{t.id.slice(-5)}</small></span><small>{t.fields.length} fields</small></button>)}</div>{!explorer.matches&&<p>No matching tokens. Try another name, address or network.</p>}<p className="neural-explorer-hint">Up to 60 nuclei in the scene. Every eligible token remains available here. Select one to inspect its data.</p></section>
  <details className="neural-activity"><summary>Live activity <span>{totals.captures} captures · {totals.observed.toLocaleString('en')} fields observed · {totals.changes.toLocaleString('en')} changed</span></summary><p>Latest 200 entries in this session. Aggregate changes are not individual trades.</p><label className="neural-log-filter">Show<select aria-label="Activity filter" value={activityFilter} onChange={e=>setActivityFilter(e.target.value)}><option value="all">All activity</option><option value="selected">Selected token</option><option value="change">Value changes</option><option value="capture">Captures</option></select></label><ol>{filteredActivity.map(e=><li key={e.id}><time>{e.at?new Date(e.at).toLocaleTimeString('en-GB',{timeZone:'UTC'}):'—'} UTC</time><span>{e.chain}</span><button disabled={!e.token||!tokens.some(t=>tokenKey(t)===e.token)} onClick={()=>e.token&&chooseToken(e.token)}>{e.text}</button>{e.kind==='change'&&<code>{String(e.before??'Not supplied').slice(0,60)} → {String(e.after).slice(0,60)}</code>}<small title={e.captureId}>Capture {e.captureId?.startsWith('combined-')?e.captureId.slice(9,17):e.captureId?.slice(0,8)}</small></li>)}</ol>{!filteredActivity.length&&<p>No matching entries in the recent session log.</p>}</details>
  <footer className="neural-footer"><span>Nucleus size: market cap · logarithmic scale. Color: network.</span><span>{capture?'Pulses show observed changes · select a token for evidence':'No observations received'}</span></footer>
 </main>;
}
